distributable:
  url: https://github.com/elm/compiler/archive/refs/tags/{{version}}.tar.gz
  strip-components: 1

versions:
  github: elm/compiler/tags

provides:
  - bin/elm

build:
  dependencies:
    haskell.org: 9 # Should be 8.4 ideally
    haskell.org/cabal: 3 # Should be 2.4 ideally
  script: |-
    cabal new-update
    cabal new-configure --ghc-option=-optl=-pthread
    cabal new-build

test:
  script: |
    elm init
    cd src
    cp $FIXTURE src/Main.elm
    elm make src/Main.elm
  fixture: |
    module Main exposing (main)
    main : String
    main = "Hello, world!"